name: Security Scan

on:
  push:
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Ejecutar Scanner
        run: |
          python scanner/scanner.py ./test_project/3version

      - name: Subir resultados SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: report.sarif

      - name: Validar resultados
        run: |
          if grep -q "CRITICAL" report.json; then
            echo "❌ Vulnerabilidades críticas encontradas"
            exit 1
          else
            echo "✅ Sin vulnerabilidades críticas"
          fi
